# Generated by Django 4.2.20 on 2025-03-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("location", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("funder", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("User", "User"), ("Admin", "Admin")],
                        default="User",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("Seed", "Seed"),
                            ("Series A", "Series A"),
                            ("Series B", "Series B"),
                        ],
                        max_length=50,
                    ),
                ),
                ("industry_fields", models.CharField(max_length=255)),
                ("eligibility_criteria", models.TextField(blank=True, null=True)),
                ("is_open_round", models.BooleanField(default=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorization",
                        to="funding.fundingevent",
                    ),
                ),
            ],
        ),
    ]
