# Generated by Django 4.2.20 on 2025-04-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0003_rename_users_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorization",
            name="application_deadline",
        ),
        migrations.RemoveField(
            model_name="categorization",
            name="funding_type",
        ),
        migrations.RemoveField(
            model_name="categorization",
            name="is_open_round",
        ),
        migrations.RemoveField(
            model_name="fundingevent",
            name="date_time",
        ),
        migrations.AddField(
            model_name="categorization",
            name="benefits",
            field=models.TextField(
                blank=True,
                help_text="Benefits or prizes offered (beneficios)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="categorization",
            name="project_type",
            field=models.CharField(
                blank=True,
                help_text="Type of project or proposal accepted (tipo_de_proyecto_o_propuesta_que_se_puede_presentar)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fundingevent",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fundingevent",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundingevent",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="fundingevent",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categorization",
            name="eligibility_criteria",
            field=models.TextField(
                blank=True,
                help_text="Criteria for participation (quienes_pueden_participar)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorization",
            name="industry_fields",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fundingevent",
            name="funder",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fundingevent",
            name="host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fundingevent",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="funding.user",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="funding.fundingevent",
                    ),
                ),
            ],
        ),
    ]
