# Generated by Django 4.2.20 on 2025-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0005_rename_user_profile_alter_application_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="unknown@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(default="Jane Smith", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
