# Generated by Django 4.2.20 on 2025-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0006_profile_age_profile_email_profile_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
